### PR TITLE
Otimization made on animation.manager

### PR DESCRIPTION
**Pull request by ensinho**
- Loop Optimization
- Early Returns
- Inline Type Inference
- Simplified Animation Creation

### CODE REVIEW

**Comment by ensinho** [comment]
Pull request on otimization at animation.manager

**Comment by keldaan-ag** [comment]
You have to use the same linter. Otherwise PR is unreadable

**Comment by ensinho** [comment]
Mb, i didnt check that earlier, hope this new one its allright, trying to avoid loops

**Comment by sylvainpolletvillard** [comment]
Its definitely not allright. Don't make PR if you don't know how to properly test and push

**Pull request closed without merging**
