### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by Ryusei0317**
add synergy_description.

### CODE REVIEW

**Comment by Ryusei0317** [comment]
add status_description.

**Comment by Ryusei0317** [comment]
add effect.

**Review by mokers-creater — CHANGES_REQUESTED** [review]
I think this is from SC2 triology, Heart of the swarm. so in my humble opinion, the translations of 'heart of the swarm' should be '군단의 심장', which is Korean translation of SC2 HOTS.

**Comment by sylvainpolletvillard** [comment]
Thanks !

**Pull request merged**
