### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by Camchanh**
Describe the changes you have conducted here

Preview the messages on https://inlang.com/github.com/Camchanh/pokemonAutoChess .

### CODE REVIEW

**Review by Camchanh — COMMENTED** [review]
added ability description

**Comment by keldaan-ag** [comment]
don't traduce words in capital letters like SPECIAL, TRUE, PHYSICAL, BURN, POISOINED, SILENCE etc...

**Comment by Camchanh** [comment]
> don't traduce words in capital letters like SPECIAL, TRUE, PHYSICAL, BURN, POISOINED, SILENCE etc...
okay :(((( but i like to translate it into Vietnamese because it is familiar to us

**Comment by keldaan-ag** [comment]
> > don't traduce words in capital letters like SPECIAL, TRUE, PHYSICAL, BURN, POISOINED, SILENCE etc...
> > okay :(((( but i like to translate it into Vietnamese because it is familiar to us

Those capital letters words are replaced during the rendering phase by their traduction in your own language + enriched text

image

**Pull request merged**
