### PR TITLE
Added Skarmory code to the game

### PR DESCRIPTION
**Pull request by Alekemon**
I tried using the tools in edit to add the graphics but can't use pack-assets with npm

### CODE REVIEW

**Comment by keldaan-ag** [comment]
for now we are using https://www.codeandweb.com/texturepacker to generate sprites in /edit/add-index.ps1

**Comment by Windchili** [comment]
Make sure to add Skarmory into the UniqueShop Array in app/types/Config.ts
This will allow it to show up in the stage 10 picks

**Comment by Alekemon** [comment]
Ok I finished adding what has been suggested

**Comment by keldaan-ag** [comment]
- new ability
- sprites needs to be generated with /edit/add-index.ps1

**Pull request closed without merging**
