### PR TITLE
Update translations (CH - Passives, Stats, Statuses, Synergies, Weather and Title etc.)

### PR DESCRIPTION
**Pull request by Benzene114**
All passive descriptions, stats and their descriptions, statuses and desc and synergy (desc) as well as weather (name and desc) are translated.

Also translated the newest pokemon names and abilities.

### CODE REVIEW

**Comment by Benzene114** [comment]
Also done the title (descs included)

**Comment by Benzene114** [comment]
Also applied changes in #2443

**Comment by Benzene114** [comment]
Also translated EN changes in #2443

**Comment by Benzene114** [comment]
also emotions and stuff.

May keep adding more before this eventually gets merge/closed and this would be the last title update for this PR.

**Comment by Benzene114** [comment]
Updated Map Names (also for JP if official names can apply)

**Comment by Benzene114** [comment]
> @Benzene114 Why is there Chinese in Japanese translation ?

Names like 暗夜遺跡? sic in Rescue Team DX, these names are (could be) pure kanji according to Bulbapedia

**Comment by sylvainpolletvillard** [comment]
OK, I trust you on this one

**Comment by sylvainpolletvillard** [comment]
Thank you !

**Pull request merged**
