### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by matiasdelre7**
ultimate pull request before 5.1? excited for the new content.

### CODE REVIEW

**Comment by sylvainpolletvillard** [comment]
the ultimate one could be after this one https://github.com/keldaanCommunity/pokemonAutoChess/pull/1788

**Comment by matiasdelre7** [comment]
leave this p.request open if you want, when the trubbish merge is done, I'll complete the translation right here.

**Comment by sylvainpolletvillard** [comment]
@matiasdelre7 it's merged

**Comment by matiasdelre7** [comment]
I don't see anything new to translate.. weird?

**Comment by matiasdelre7** [comment]
Finished! Great job Curry and Keldaan^^ 5.1 is here!

**Pull request merged**
